name: CI
on:
  push:
    branches:
      - master

jobs:
  test: 
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v2

    - name: Run unit test
      run: go test ./...

  build:
    needs: test
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lacak-lamaran:latest
  deployment:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            whoami
            if [ "$(docker ps -aq -f name=lacak-lamaran)" ]; then
              docker stop lacak-lamaran
              docker rm lacak-lamaran
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/lacak-lamaran:latest
            docker run -d -p 1213:1213 --name lacak-lamaran ${{ secrets.DOCKER_USERNAME }}/lacak-lamaran:latest